/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package majorproject.Modules;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author avinash
 */
public class BookedHistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookedHistory
     */
    DatabaseUserAndPassword obj = new DatabaseUserAndPassword();
    String user = obj.user;
    String pass = obj.pass;
    
    public BookedHistory() {
        initComponents();
        LoadTableData();
    }
    
     Connection con;
     PreparedStatement pt;
    public void LoadTableData(){
        
        try {
            // TODO add your handling code here:
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/MyAirlineSystem",user,pass);
            
            
            pt = con.prepareStatement("select *from Tickets");
            
            
            
            ResultSet rs =pt.executeQuery();
            ResultSetMetaData rm = rs.getMetaData();
            
            int c;
            c =rm.getColumnCount();
            
            DefaultTableModel table  = (DefaultTableModel)jTable1.getModel();
            table.setRowCount(0);
            
            while(rs.next())
            {
                Vector vect = new Vector();
                for(int i=1;i<=c;i++)
                {
                    vect.add(rs.getString("ticketno"));
                    vect.add(rs.getString("flightno"));
                    vect.add(rs.getString("flightname"));
                    vect.add(rs.getString("class"));
                    vect.add(rs.getString("source"));
                    vect.add(rs.getString("destination"));
                    vect.add(rs.getString("arrival"));
                    vect.add(rs.getString("departure"));
                    vect.add(rs.getString("date"));
                    vect.add(rs.getString("price"));
                    vect.add(rs.getString("seats"));
                    vect.add(rs.getString("custid"));
                    vect.add(rs.getString("firstname"));
                    vect.add(rs.getString("lastname"));
                }
                table.addRow(vect);
            }
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookTickets.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setResizable(false);
        setPreferredSize(new java.awt.Dimension(800, 490));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)), "Booked Tickets History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket No.", "Flight No.", "Flight Name", "Class", "Source", "Destination", "Arrival", "Departure", "Date", "Price", "Seats", "Cust. ID", "First Name", "Last Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 27, 720, 350));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.setVisible(false);
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
