/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package majorproject.Modules;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author avinash
 */
public class PrintFormat extends javax.swing.JFrame {

    /**
     * Creates new form PrintTickets
     */
    
    PrintTickets ptkt = new  PrintTickets();
             String tk  =  ptkt.ticket;
             
    
    public PrintFormat() {
        initComponents();
        autoincreament();
        fetchdata();
    }

    
    Connection con;
    PreparedStatement pt;
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     public void autoincreament(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/MyAirlineSystem","root","0326@Mysql");

           Statement s = con.createStatement();
           ResultSet rs =s.executeQuery("select MAX(ticketno) from Tickets");
           
           rs.next();
           rs.getString("MAX(ticketno)");
           
           if(rs.getString("MAX(ticketno)")==null){
               
               txtgateno.setText("GATE-01");
               txtseatno1.setText("EC5-01");
               txtseatno2.setText("EC5-01");
               txtseqno.setText("QU-101");
           }
           else
           {
               long id = Long.parseLong(rs.getString("MAX(ticketno)").substring(2, rs.getString("MAX(ticketno)").length()));
               id++;
               txtgateno.setText("GATE-"+String.format("%01d", id));
               txtseatno1.setText("EC-5"+String.format("%01d", id));
               txtseatno2.setText("EC-5"+String.format("%01d", id));
               txtseqno.setText("QU-1"+String.format("%02d", id));
           }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrintFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PrintFormat.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
     
     public void fetchdata(){
         
         
         String tkt = tk;
         
          try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/MyAirlineSystem","root","0326@Mysql");
               
                
                pt = con.prepareStatement("select *from Tickets where ticketno = ?");
                
                pt.setString(1,tkt);
                
                ResultSet rs =pt.executeQuery();
                
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this, "Ticket Not Found");
                }
                else{
                    String firstname = rs.getString("firstname");
                    String lastname = rs.getString("lastname");
                    String source = rs.getString("source");
                    String dept = rs.getString("departure");
                    String arrival = rs.getString("arrival");
                    String flightno = rs.getString("flightno");
                    String ticket = rs.getString("ticketno");
                    String date = rs.getString("date");
                    
                    
                    
                    txtfirstname.setText(firstname);
                    txtlastname.setText(lastname);
                    txtsource.setText(source);
                    txtdept.setText(dept);
                    txtarrival.setText(arrival);
                    txtflightno1.setText(flightno);
                    txtflightno2.setText(flightno);
                    tktno.setText(ticket);
                    tktdate1.setText(date);
                    txtdate2.setText(date);
                   
                   
                    
                }
                
                
               
              //  JOptionPane.showMessageDialog(this, "Data Fetched Sucessfully");
                
                
            }
            catch(SQLException ex){
             ex.getStackTrace();
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrintFormat.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        txtsource = new javax.swing.JLabel();
        txtdestination = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtflightno1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtgateno = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtarrival = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtseatno1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtseatno2 = new javax.swing.JLabel();
        txtdate2 = new javax.swing.JLabel();
        txtflightno2 = new javax.swing.JLabel();
        tktno = new javax.swing.JLabel();
        tktdate1 = new javax.swing.JLabel();
        txtseqno = new javax.swing.JLabel();
        txtdept = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 2));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 2, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/majorproject/image/airplane-logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Avinash Airlines");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 30));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Your departure terminal is T1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 220, 30));

        txtfirstname.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtfirstname.setText("Firstnane");
        jPanel1.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 20));

        txtlastname.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtlastname.setText("Lastname");
        jPanel1.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        txtsource.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtsource.setText("Source");
        jPanel1.add(txtsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 90, -1));

        txtdestination.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtdestination.setText("Destination");
        jPanel1.add(txtdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 90, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel8.setText("To");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Flight");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtflightno1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtflightno1.setText("FNo.");
        jPanel4.add(txtflightno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 100));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Gate No.");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtgateno.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtgateno.setText("A-1");
        jPanel8.add(txtgateno, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 53, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 100));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Boarding Time ");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        txtarrival.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtarrival.setText("BT");
        jPanel9.add(txtarrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 100));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Seat");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 20));

        txtseatno1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtseatno1.setText("15E");
        jPanel10.add(txtseatno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 100, 100));

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("Boarding Pass(Web check--in)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 220, 30));

        jLabel18.setText("Date :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel19.setText("Departure :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jLabel20.setText("Seq :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel21.setText("Ticket No. ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel22.setText("Flight No.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jLabel23.setText("Date :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel24.setText("Seat No.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        txtseatno2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtseatno2.setText("15E");
        jPanel1.add(txtseatno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        txtdate2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtdate2.setText("date");
        jPanel1.add(txtdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        txtflightno2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtflightno2.setText("flight");
        jPanel1.add(txtflightno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        tktno.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        tktno.setText("FNo.");
        jPanel1.add(tktno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        tktdate1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        tktdate1.setText("DT");
        jPanel1.add(tktdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        txtseqno.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtseqno.setText("jLabel14");
        jPanel1.add(txtseqno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        txtdept.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txtdept.setText("Dept.");
        jPanel1.add(txtdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintFormat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel tktdate1;
    private javax.swing.JLabel tktno;
    private javax.swing.JLabel txtarrival;
    private javax.swing.JLabel txtdate2;
    private javax.swing.JLabel txtdept;
    private javax.swing.JLabel txtdestination;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtflightno1;
    private javax.swing.JLabel txtflightno2;
    private javax.swing.JLabel txtgateno;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtseatno1;
    private javax.swing.JLabel txtseatno2;
    private javax.swing.JLabel txtseqno;
    private javax.swing.JLabel txtsource;
    // End of variables declaration//GEN-END:variables
}
