/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package majorproject.Modules;

import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement; 
import java.sql.SQLException;
import java.text.DateFormat; 
import java.text.SimpleDateFormat;
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Date;

/**
 *
 * @author avinash
 */
public class PrintTickets extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrintTickkets
     */
     DatabaseUserAndPassword obj = new DatabaseUserAndPassword();
    String user = obj.user;
    String pass = obj.pass;
    
    public PrintTickets() {
        initComponents();
        
    }
    
    
    static String ticket;

    Connection conn;
    PreparedStatement pt;
    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.The content of this method is always
 regenerated by the Form Editor.
     * @param tn
     * @return 
     */
    @SuppressWarnings("unchecked")
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tktno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtfirstname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        txtsource = new javax.swing.JLabel();
        txtdestination = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtarrival = new javax.swing.JLabel();
        txtdeparture = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generate Tickets", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Ticket No.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel2.add(tktno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, 30));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 30));

        jLabel2.setText("Name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Source :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Destination :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Arrival Time :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, 40));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 90, 40));
        jPanel2.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jPanel2.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));
        jPanel2.add(txtsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        jPanel2.add(txtdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel10.setText("Departure Time :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel2.add(txtarrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        jPanel2.add(txtdeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 550, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
          String ticketno = tktno.getText();
          
            try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/MyAirlineSystem",user,pass);
               
                
                pt = conn.prepareStatement("select *from Tickets where ticketno = ?");
                
                pt.setString(1,ticketno);
                
                ResultSet rs =pt.executeQuery();
                
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this, "Ticket Not Found");
                }
                else{
                    String firstname = rs.getString("firstname");
                    String lastname = rs.getString("lastname");
                    String source = rs.getString("source");
                    String destination = rs.getString("destination");
                    String arrival = rs.getString("arrival");
                    String departure = rs.getString("departure");
                    
                    
                    
                    txtfirstname.setText(firstname);
                    txtlastname.setText(lastname);
                    txtsource.setText(source);
                    txtdestination.setText(destination);
                    txtarrival.setText(arrival);
                    txtdeparture.setText(departure);
                   
                    
                }
                
                
               
              //  JOptionPane.showMessageDialog(this, "Data Fetched Sucessfully");
                
                
            }
            catch(SQLException ex){
             ex.getStackTrace();
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrintTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.setVisible(false);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
          
        
        String ticketno = tktno.getText();
          
        ticket =ticketno;
        
            
            try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/MyAirlineSystem",user,pass);
               
                
                pt = conn.prepareStatement("select *from Tickets where ticketno = ?");
                
                pt.setString(1,ticketno);
                
                ResultSet rs =pt.executeQuery();
                
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this, "Ticket Not Found Please Check Your Ticket No.");
                }
                else{
                    
                    PrintFormat pf = new PrintFormat();
                         pf.setVisible(true);
                        
                }
                
                            
            }
            catch(SQLException ex){
             ex.getStackTrace();
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrintTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tktno;
    private javax.swing.JLabel txtarrival;
    private javax.swing.JLabel txtdeparture;
    private javax.swing.JLabel txtdestination;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtsource;
    // End of variables declaration                   
}
